name: train-times

services:
  train-times-frontend:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        EXPO_PUBLIC_TRANSPORT_API_APP_ID: ${EXPO_PUBLIC_TRANSPORT_API_APP_ID}
        EXPO_PUBLIC_TRANSPORT_API_APP_KEY: ${EXPO_PUBLIC_TRANSPORT_API_APP_KEY}
        EXPO_PUBLIC_USE_MOCK_API: ${EXPO_PUBLIC_USE_MOCK_API}
    container_name: train-times-frontend
    restart: always
    networks:
      - train-times-net

networks:
  train-times-net:
    name: train-times-net
